# Generated by Django 4.2.7 on 2023-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='Mobile_No',
            field=models.IntegerField(max_length=12),
        ),
    ]
